pipeline {
    agent any
    stages {
        //stage ('Build') {
        //    steps {
        //        dir("app") {
        //     sh 'npm install'
        //    }
                
        //    }
      //  }
        

        
        stage ('Docker-build') {
            steps {
                 dir("app") {
                 sh "docker build -t alielkhatteb/nodeserver:latest ."
               }
               dir("nginx") {
                 sh "docker build -t alielkhatteb/nginx:latest ../nginx"   
               }  
           }
        }

        stage("DockerPush"){
            steps {
            withCredentials([string(credentialsId: 'dockerhub', variable: 'dockerhub')]) {
                    sh "docker login -u alielkhatteb -p ${dockerhub}"
                    sh "docker push alielkhatteb/nodeserver:latest"
                    sh "docker push alielkhatteb/nginx:latest"
            } 
            }
        }

        stage("docker deploy"){

                steps {
			    sshagent(['ec2-t1']) {
			        
				    sh 'ssh -o StrictHostKeyChecking=no ec2-user@54.226.219.225 '
				    sh "docker-compose pull  && docker-compose up -d"
			    }
                sshagent(['ec2-t2']) {
				    sh 'ssh -o StrictHostKeyChecking=no ec2-user@54.227.91.39 '
				    sh "docker-compose pull  && docker-compose up -d"
			    }
			}
        }
    }
}
